version: '3.3'
services:
    postgres:
        restart: always
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - "./data:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: atlassian
            POSTGRES_PASSWORD: atlassian2019
